# Configuração padrão do ESK_NMAP
scan_profiles:
  basic:
    name: Scan Básico
    description: Scan rápido para visão geral da rede
    options: ["-T5", "-sn"]  # Mantemos -sn para rápida descoberta, mas sem -n para permitir resolução DNS
    ports: "21,22,23,25,53,80,443,3389"
    timing: 5
  
  stealth:
    name: Scan Silencioso
    description: Scan mais discreto usando SYN stealth
    options: ["-sS", "-T2", "-n"]
    ports: "21-23,25,53,80,443,3306,3389"
    timing: 2
  
  version:
    name: Scan com Detecção de Versão
    description: Scan com identificação de serviços
    options: ["-sV", "-T4", "-n"]
    ports: "21-23,25,53,80,443,3306,3389,8080"
    timing: 4
  
  complete:
    name: Scan Completo
    description: Scan detalhado com scripts NSE
    options: ["-sV", "-sC", "-O", "-T4", "-n"]
    ports: "1-1024,3306,3389,5432,8080,8443"
    timing: 4

  quick:
    name: Scan Rápido
    description: Scan rápido com opções mínimas
    options: ["-T5", "-F", "-n"]
    ports: "80,443"
    timing: 5

  discovery:
    name: Scan de Descoberta
    description: Scan para encontrar hostnames e portas comuns
    options: ["-T4", "-F"]  # Removido --source-port 53 para melhorar a detecção de portas
    ports: ""  # Deixamos a lista de portas vazia para usar o padrão do nmap com -F
    timing: 4
    
  # Novo perfil que mantém a opção source-port para contornar firewalls específicos
  bypass:
    name: Scan Bypass Firewall
    description: Scan tentando contornar firewalls usando porta de origem específica
    options: ["-T4", "-F", "--source-port", "53"]  # Usa --source-port 53 para tentar passar por firewalls
    ports: ""  # Deixamos a lista de portas vazia para usar o padrão do nmap com -F
    timing: 4

timeouts:
  discovery: 300  # Aumentado de 180 para 300 segundos
  port_scan: 600
  version_scan: 300

retry:
  max_attempts: 3
  delay_between_attempts: 5

reporting:
  format: text
  include_closed_ports: false
  group_by_port: true

environment: development
log_level:
  development: DEBUG
  production: INFO